apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipe
  template:
    metadata:
      labels:
        app: pipe
    spec:
      containers:
        - name: pipe
          image: pipe_img
          env:
            - name: KAFKA_BROKER
              value: "kafka:9093"
