version: '3'
services:
  kafka:
    build: kafka
    networks:
      - kafka-net
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:9093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - #      - KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml

    
    
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    expose:
      - '29092'
      - '1099'
    volumes:
      - ./jmx_exporter:/usr/share/jmx_exporter/
  
  
  producer:
    image: producer_img
    networks:
      - kafka-net
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:29092"


  consumer:
    image: consumer_img
    networks:
      - kafka-net
    depends_on:
      - kafka
      - pipe
    environment:
      KAFKA_BROKER: "kafka:29092"


  pipe:
    image: pipe_img
    networks:
      - kafka-net
    depends_on:
      - kafka
      - producer
    environment:
      KAFKA_BROKER: "kafka:29092"

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    depends_on:
      - kafka
    networks:
      - kafka-net
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - kafka-net
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - kafka-net
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:



networks:
  kafka-net:
