version: '3'
services:
  kafka:
    #    image: apache/kafka:4.0.0
    build: .\kafka

    container_name: kafka
    #    hostname: kafka
    environment:

      CLUSTER_ID: "kafka-cluster"
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093 #,PROM://0.0.0.0:7071
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093 #,PROM://kafka:7071

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_ADVERTISED_HOST_NAME: kafka

    ports:
      - "9092:9092"
      - "9991:9991"
      - "7071:7071"
      - "7070:7070"
    volumes:
      - ./kafka/jmx_exporter:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock




  producer:
    image: producer_img

    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9093"

  consumer:
    image: consumer_img

    depends_on:
      - kafka
      - pipe
    environment:
      KAFKA_BROKER: "kafka:9093"

  pipe:
    image: pipe_img

    depends_on:
      - kafka
      - producer
    environment:
      KAFKA_BROKER: "kafka:9093"

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka



  prometheus:
    image: prom/prometheus:latest

    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest

    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

