version: '3.8'

x-kafka-common: &kafka-common
  image: 'bitnami/kafka:latest'
  ports:
    - "9092"
  networks:
    - kafka
  healthcheck:
    test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9092; exit $$?;'"
    interval: 5s
    timeout: 10s
    retries: 3
    start_period: 30s
#  restart: unless-stopped

x-kafka-env-common: &kafka-env-common
  KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
  # connections
  ALLOW_PLAINTEXT_LISTENER: 'yes'
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  # monitoring
  EXTRA_ARGS: " -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-1.2.0.jar=9404:/opt/jmx-exporter/kafka-jmx.yml"
  # replication
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
  KAFKA_CFG_REPLICATION_FACTOR: 3
  KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
  KAFKA_CFG_NUM_PARTITIONS: 6



x-kafka-service: &kafka-service
  networks:
    - kafka
  depends_on:
    - kafka-0
    - kafka-1
    - kafka-2

x-kafka-service-env: &kafka-service-env
  KAFKA_BROKER: "kafka-0:9092,kafka-1:9092,kafka-2:9092"

services:

  kafka-0:
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 0
    volumes:
      #      - kafka_0_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter

  kafka-1:
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 1
    volumes:
      #      - kafka_1_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter

  kafka-2:
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 2
    volumes:
      #      - kafka_2_data:/bitnami/kafka
      - ./jmx-exporter:/opt/jmx-exporter


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka-0
      - kafka-1
    networks:
      - kafka
    ports:
      - '8080:8080'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - kafka
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:9090 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - kafka
    healthcheck:
      test: curl --fail localhost:3000
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s


  producer:
    image: producer_img
    <<: *kafka-service
    environment:
      <<: *kafka-service-env
      MESSAGE_RATE: 20

  consumer:
    image: consumer_img
    <<: *kafka-service
    environment:
      <<: *kafka-service-env

  pipe:
    image: pipe_img
    <<: *kafka-service
    environment:
      <<: *kafka-service-env

networks:
  kafka:

volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  prom_data:
    driver: local