version: '3'
services:
  kafka:
    image: apache/kafka:4.0.0

    #    networks:
    #      - kafka-net
    container_name: kafka
    #    hostname: kafka
    environment:

      CLUSTER_ID: "kafka-cluster"
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Djava.rmi.server.hostname=kafka \
  -Djava.net.preferIPv4Stack=true \
  -Dcom.sun.management.jmxremote.rmi.port=7070 \
  -Dcom.sun.management.jmxremote.local.only=false \
  -javaagent:/usr/app/jmx_prometheus_javaagent-1.2.0.jar=kafka:7071:/usr/app/prom-jmx-agent-config.yaml"
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/jmx_exporter:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock




  producer:
    image: producer_img
    #    networks:
    #      - kafka-net
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9093"

  consumer:
    image: consumer_img
    #    networks:
    #      - kafka-net
    depends_on:
      - kafka
      - pipe
    environment:
      KAFKA_BROKER: "kafka:9093"

  pipe:
    image: pipe_img
    #    networks:
    #      - kafka-net
    depends_on:
      - kafka
      - producer
    environment:
      KAFKA_BROKER: "kafka:9093"

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka


  #  kafdrop:
  #    image: obsidiandynamics/kafdrop
  #    depends_on:
  #      - kafka
  #    #    networks:
  #    #      - kafka-net
  #    environment:
  #      KAFKA_BROKERCONNECT: kafka:9093
  #    ports:
  #      - "9000:9000"

  prometheus:
    image: prom/prometheus:latest
    #    networks:
    #      - kafka-net
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    #    networks:
    #      - kafka-net
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  kafka-net:
