apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipe
  template:
    metadata:
      labels:
        app: pipe
    spec:
      containers:
        - name: pipe
          image: pipe_img
          envFrom:
            - configMapRef:
                name: kafka-broker-config