server:
  extraScrapeConfigs:
    - job_name: 'kafka'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs:
        - targets: [ 'my-kafka-jmx-metrics.default.svc.cluster.local:5556' ]