apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-cluster
data:
  KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093,2@kafka-2.kafka-headless:9093"
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  EXTRA_ARGS: " -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-1.2.0.jar=9404:/opt/jmx-exporter/kafka-jmx.yml"
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
  KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
  KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "2"
  KAFKA_CFG_REPLICATION_FACTOR: "3"
  KAFKA_CFG_MIN_INSYNC_REPLICAS: "2"
  KAFKA_CFG_NUM_PARTITIONS: "6"


---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-cluster
spec:
  ports:
    - name: plaintext
      port: 9092
  clusterIP: None
  selector:
    app: kafka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-cluster
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9404
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_NODE_ID
              value: "$((${POD_NAME##*-} % 3))"
          volumeMounts:
            - name: jmx-exporter
              mountPath: /opt/jmx-exporter
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: jmx-exporter
          hostPath:
            path: ./jmx-exporter
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi